openapi: 3.0.0
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  description: >-
    This is a sample server Petstore server.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
    #swagger](http://swagger.io/irc/).  For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /pet/{petId}:
    get:
      tags:
        - pet
      summary: gets a pet by id
      description: ''
      operationId: updatePetWithForm
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
      responses:
        '405':
          description: Invalid input
    delete:
      tags:
        - pet
      summary: gets a pet by id
      description: ''
      operationId: updatePetWithForm
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
      responses:
        '405':
          description: Invalid input
  /calc/{petId}:
    get:
      tags:
        - pet
      summary: gets a pet by id
      description: ''
      operationId: updatePetWithForm
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
      responses:
        '405':
          description: Invalid input

components:
  schemas:
    JumpEvent:
      type: "object"
      required:
        - user_id
      x-tira:
        retention-time:
          volatile: true
        special_category:
          category: "Health Data"
        profiling:
          reason: "Health profile based on series of health related behaviour."
      properties:
        seconds:
          type: "integer"
        datetime:
          type: "string"
        user_id:
          type: "integer"
    ToothbrushEvent:
      type: "object"
      required:
        - user_id
      properties:
        seconds:
          type: "integer"
        datetime:
          type: "string"
        user_id:
          type: "integer"
    SameEvent:
      type: "object"
      x-tira:
        retention-time:
          volatile: true
      required:
        - user_id
      properties:
        seconds:
          type: "integer"
        datetime:
          type: "string"
        user_id:
          type: "integer"