openapi: 3.0.0
x-tira:
  utilizer:
    - name: "AWS"
      non_eu_country: true
      country: "UK"
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  description: >-
    This is a sample server Petstore server.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
    #swagger](http://swagger.io/irc/).  For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /pet/{petId}:
    get:
      tags:
        - pet
      summary: gets a pet by id
      description: ''
      operationId: updatePetWithForm
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
      responses:
        '405':
          description: Invalid input
    delete:
      tags:
        - pet
      summary: gets a pet by id
      description: ''
      operationId: updatePetWithForm
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
      responses:
        '405':
          description: Invalid input
  /calc/{petId}:
    get:
      tags:
        - pet
      summary: gets a pet by id
      description: ''
      operationId: updatePetWithForm
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
      responses:
        '405':
          description: Invalid input

components:
  schemas:
    DanceEvent:
      type: "object"
      required:
        - user_id
      x-tira:
        retention-time:
          volatile: true
        special_category:
          category: "Health Data"
        purposes:
          yappl:
            '{
                         "id":123,
                         "preference":[
                            {
                               "rule":{
                                  "purpose":{
                                     "permitted": [ "FitnessData Sharing", "Health Insurance Bonus Program" ],
                                     "excluded": [ ... ]
                                  },
                                  "utilizer":{
                                     "permitted": [ ... ],
                                     "excluded": [ ... ]
                                  },
                                  "transformation": [ ... ],
                                  "valid_from":"2021-06-09T00:00:00.000Z",
                                  "exp_date":"0000-01-01T00:00:00.000Z"
                               }
                            }
                         ]
                      }'
        profiling:
          reason: "Health profile based on series of health related behaviour."
        utilizer:
          - name: "MyFitnessPal"
            non_eu_country: false
          - name: "Strava"
            non_eu_country: true
            country: "USA"
        utilizer_category:
          - name: "Health Insurance Company"
            country: "Germany"
            non_eu_country: false
            type: "Insurance Company"
            sector: "Insurance"
            sub_sector:
              - "Health Insurance"
              - "Health Tax"
      properties:
        seconds:
          type: "integer"
        datetime:
          type: "string"
        user_id:
          type: "integer"
    ToothbrushEvent:
      type: "object"
      required:
        - user_id
      properties:
        seconds:
          type: "integer"
        datetime:
          type: "string"
        user_id:
          type: "integer"
    SameEvent:
      type: "object"
      x-tira:
        retention-time:
          volatile: true
        special_category:
          category: "Health Data"
      required:
        - user_id
      properties:
        seconds:
          type: "integer"
        datetime:
          type: "string"
        user_id:
          type: "integer"